#!/usr/bin/env bash
set -euo pipefail

api_key="${NVIDIA_API_KEY:-${1:-}}"
repo_root="${MAIW_ROOT:-/maiw}"
brev_dir="${repo_root}/deploy/brev"
env_file="${brev_dir}/.env"

if [ -z "$api_key" ]; then
  echo "Missing NVIDIA API key" >&2
  exit 2
fi

if ! LC_ALL=C printf '%s' "$api_key" | grep -Eq '^nvapi-[A-Za-z0-9._-]+$'; then
  echo "Expected an NVIDIA API key beginning with nvapi- and containing only letters, numbers, dots, underscores, or hyphens." >&2
  exit 2
fi

mkdir -p "${brev_dir}/generated/docker-config"
mkdir -p \
  /ephemeral/maiw/postgres \
  /ephemeral/maiw/redis \
  /ephemeral/maiw/kafka \
  /ephemeral/maiw/etcd \
  /ephemeral/maiw/minio \
  /ephemeral/maiw/milvus \
  /ephemeral/maiw/nim-cache \
  /ephemeral/maiw/nim-models

read_existing() {
  key="$1"
  if [ -f "$env_file" ]; then
    grep -E "^${key}=" "$env_file" | tail -n 1 | cut -d= -f2- || true
  fi
}

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

postgres_password="$(read_existing POSTGRES_PASSWORD)"
jwt_secret_key="$(read_existing JWT_SECRET_KEY)"

if [ -z "$postgres_password" ]; then
  postgres_password="$(random_hex)"
fi

if [ -z "$jwt_secret_key" ]; then
  jwt_secret_key="$(random_hex)$(random_hex)"
fi

tmp_file="$(mktemp)"
umask 077
{
  printf '%s\n' '# Generated by deploy/brev OliveTin.'
  printf '%s\n' '# Do not commit this file.'
  printf '%s\n' ''
  printf '%s\n' 'ENVIRONMENT=development'
  printf '%s\n' ''
  printf '%s\n' 'POSTGRES_USER=warehouse'
  printf 'POSTGRES_PASSWORD=%s\n' "$postgres_password"
  printf '%s\n' 'POSTGRES_DB=warehouse'
  printf '%s\n' 'DB_HOST=timescaledb'
  printf '%s\n' 'DB_PORT=5432'
  printf '%s\n' 'PGPORT=5435'
  printf '%s\n' ''
  printf 'JWT_SECRET_KEY=%s\n' "$jwt_secret_key"
  printf '%s\n' 'REDIS_HOST=redis'
  printf '%s\n' 'REDIS_PORT=6379'
  printf '%s\n' 'REDIS_PASSWORD='
  printf '%s\n' 'REDIS_DB=0'
  printf '%s\n' ''
  printf '%s\n' 'MILVUS_HOST=milvus'
  printf '%s\n' 'MILVUS_PORT=19530'
  printf '%s\n' 'MILVUS_USER=root'
  printf '%s\n' 'MILVUS_PASSWORD=Milvus'
  printf '%s\n' 'MILVUS_USE_GPU=true'
  printf '%s\n' 'MILVUS_GPU_DEVICE_ID=0'
  printf '%s\n' 'CUDA_VISIBLE_DEVICES=0,1,2,3'
  printf '%s\n' 'MILVUS_INDEX_TYPE=GPU_CAGRA'
  printf '%s\n' 'MILVUS_COLLECTION_NAME=warehouse_docs_gpu'
  printf '%s\n' ''
  printf '%s\n' 'KAFKA_BOOTSTRAP_SERVERS=kafka:9092'
  printf '%s\n' ''
  printf '%s\n' 'MINIO_ROOT_USER=minioadmin'
  printf '%s\n' 'MINIO_ROOT_PASSWORD=minioadmin'
  printf '%s\n' 'MINIO_ACCESS_KEY=minioadmin'
  printf '%s\n' 'MINIO_SECRET_KEY=minioadmin'
  printf '%s\n' ''
  printf 'NVIDIA_API_KEY=%s\n' "$api_key"
  printf 'EMBEDDING_API_KEY=%s\n' "$api_key"
  printf 'RAIL_API_KEY=%s\n' "$api_key"
  printf 'NEMO_RETRIEVER_API_KEY=%s\n' "$api_key"
  printf 'NEMO_OCR_API_KEY=%s\n' "$api_key"
  printf 'NEMO_PARSE_API_KEY=%s\n' "$api_key"
  printf 'LLAMA_NANO_VL_API_KEY=%s\n' "$api_key"
  printf 'LLAMA_49B_API_KEY=%s\n' "$api_key"
  printf '%s\n' ''
  printf '%s\n' 'LLM_NIM_IMAGE=nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1.5:2.0.6'
  printf '%s\n' 'LLM_NIM_URL=http://llm-nim:8000/v1'
  printf '%s\n' 'LLM_NIM_PORT=8000'
  printf '%s\n' 'LLM_MODEL=nvidia/llama-3.3-nemotron-super-49b-v1.5'
  printf '%s\n' 'LLM_TEMPERATURE=0.1'
  printf '%s\n' 'LLM_MAX_TOKENS=2000'
  printf '%s\n' 'LLM_TOP_P=1.0'
  printf '%s\n' 'LLM_FREQUENCY_PENALTY=0.0'
  printf '%s\n' 'LLM_PRESENCE_PENALTY=0.0'
  printf '%s\n' 'LLM_CLIENT_TIMEOUT=120'
  printf '%s\n' 'LLM_CACHE_ENABLED=true'
  printf '%s\n' 'LLM_CACHE_TTL_SECONDS=300'
  printf '%s\n' ''
  printf '%s\n' 'EMBEDDING_NIM_URL=https://integrate.api.nvidia.com/v1'
  printf '%s\n' 'EMBEDDING_MODEL=nvidia/llama-nemotron-embed-vl-1b-v2'
  printf '%s\n' 'EMBEDDING_DIMENSION=2048'
  printf '%s\n' ''
  printf '%s\n' 'RAIL_API_URL=https://integrate.api.nvidia.com/v1'
  printf '%s\n' 'LLAMA_49B_TIMEOUT=120'
  printf '%s\n' ''
  printf '%s\n' 'CORS_ORIGINS=http://localhost:3001,http://localhost:3000,http://127.0.0.1:3001,http://127.0.0.1:3000'
  printf '%s\n' 'MAX_REQUEST_SIZE=10485760'
  printf '%s\n' 'MAX_UPLOAD_SIZE=52428800'
} > "$tmp_file"

mv "$tmp_file" "$env_file"
chmod 600 "$env_file"
if [ "$(id -u)" = "0" ]; then
  repo_owner="$(stat -c '%u:%g' "$brev_dir" 2>/dev/null || true)"
  if [ -n "$repo_owner" ]; then
    chown "$repo_owner" "$env_file"
  fi
fi

login_output="$(mktemp)"
if printf '%s' "$api_key" | docker login nvcr.io -u '$oauthtoken' --password-stdin >"$login_output" 2>&1; then
  rm -f "$login_output"
  echo "Configured Docker login for nvcr.io using the supplied NVIDIA API key."
else
  login_status="$?"
  echo "Could not authenticate with the NGC Registry at nvcr.io using the supplied NVIDIA API key." >&2
  echo "Docker reported:" >&2
  sed 's/^/  /' "$login_output" >&2
  rm -f "$login_output"
  echo "" >&2
  echo "Check that the key is a valid NVIDIA API key and has access to the NGC Catalog / nvcr.io registry." >&2
  exit "$login_status"
fi
