# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
ExecutionRegistry — single-process in-memory idempotency store.

Phase 10E Batch 1 — Idempotency Contract
Phase 10E Batch 3 — Reconciliation support (intent snapshot, ReconciliationRecord)

SINGLE-PROCESS SAFETY
---------------------
Idempotency guarantees provided by this registry are valid only within one
process instance. Distributed / multi-replica idempotency requires a shared
external store and is out of scope for Batch 1.

Identity relationships
----------------------
execution_id    : One logical execution attempt. Generated by BaseActionExecutor
                  before the write. Stable across guard checks and the write call.
idempotency_key : Identity of the intended logical mutation. Caller-supplied via
                  ActionProposal.idempotency_key. Same key + same capability =
                  same logical operation; re-submission does not produce a second
                  physical mutation.

Unresolved-target guard (v2.0.1 round 3, NEW3-P1-02)
---------------------------------------------------
A write whose outcome is UNKNOWN (or still in flight) may have changed its
target.  Until it is reconciled to CONFIRMED_EXECUTED / CONFIRMED_NOT_EXECUTED,
``begin()`` refuses every new write to the same domain target (e.g. equipment
asset FL-01) — even under a new proposal, decision and execution_id — by
returning the blocking record.  This is what stops an operator's identical
retry from executing a second consequential write (third re-audit, §50).
``JsonFileExecutionRegistry`` makes the records — and therefore the guard —
survive a process crash / restart.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .outcome import ExecutionOutcome
from .reconciliation import ExecutionIntent, ReconciliationRecord, ReconciliationOutcome

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


@dataclass
class ExecutionRecord:
    """A single recorded execution attempt."""

    execution_id: str
    idempotency_key: str | None
    capability: str
    proposal_id: str
    started_at: datetime
    outcome: ExecutionOutcome | None = None  # None = in-progress
    completed_at: datetime | None = None
    result: Any = None  # ActionExecutionResult once complete
    intent: ExecutionIntent | None = None  # Immutable snapshot captured at begin() time
    reconciliation: ReconciliationRecord | None = None  # Set by set_reconciliation()
    # True when the record was found in flight after a restart and turned into
    # UNKNOWN (the process died while the write may have been on the wire).
    recovered_after_restart: bool = False

    @property
    def domain(self) -> str:
        parts = self.capability.split(".")
        return parts[1] if len(parts) >= 3 else self.capability

    @property
    def target(self) -> str | None:
        return self.intent.target if self.intent is not None else None

    @property
    def unresolved(self) -> bool:
        """In flight, or UNKNOWN without a definitive reconciliation."""
        if self.outcome is None:
            return True
        if self.outcome == ExecutionOutcome.UNKNOWN:
            return self.reconciliation is None or (
                self.reconciliation.outcome == ReconciliationOutcome.INDETERMINATE
            )
        return False

    @property
    def effective_status(self) -> str:
        """
        Derived operational view of this execution record.

        Returns
        -------
        "in_progress"           — outcome is None (write not yet complete)
        "effectively_executed"  — UNKNOWN + reconciliation CONFIRMED_EXECUTED
        "effectively_not_executed" — UNKNOWN + reconciliation CONFIRMED_NOT_EXECUTED
        "unknown"               — UNKNOWN + no reconciliation or INDETERMINATE
        "{outcome.value}"       — any other completed outcome
        """
        if self.outcome is None:
            return "in_progress"
        if self.outcome == ExecutionOutcome.UNKNOWN:
            if self.reconciliation is None:
                return "unknown"
            if self.reconciliation.outcome == ReconciliationOutcome.CONFIRMED_EXECUTED:
                return "effectively_executed"
            if (
                self.reconciliation.outcome
                == ReconciliationOutcome.CONFIRMED_NOT_EXECUTED
            ):
                return "effectively_not_executed"
            return "unknown"  # INDETERMINATE
        return self.outcome.value


class ExecutionRegistry:
    """
    Single-process in-memory idempotency store for warehouse write executions.

    Usage
    -----
    At executor startup:
        registry = ExecutionRegistry()

    In BaseActionExecutor.execute():
        existing = registry.begin(execution_id, idempotency_key, capability, proposal_id)
        if existing is not None:
            return _idempotent_result(existing)
        # ... perform write ...
        registry.complete(execution_id, outcome, result)
        # OR on ambiguous write:
        registry.mark_unknown(execution_id)
    """

    def __init__(self) -> None:
        self._by_execution_id: dict[str, ExecutionRecord] = {}
        self._by_idempotency_key: dict[str, ExecutionRecord] = {}

    def begin(
        self,
        execution_id: str,
        idempotency_key: str | None,
        capability: str,
        proposal_id: str,
        intent: ExecutionIntent | None = None,
    ) -> ExecutionRecord | None:
        """
        Register the start of a new execution attempt.

        Parameters
        ----------
        intent : ExecutionIntent | None
            Compact immutable snapshot of write intent. Stored in the
            ExecutionRecord so reconciliation has everything it needs without
            a reference back to the original ActionProposal.

        Returns
        -------
        None
            This is a fresh execution — proceed with the write.
        ExecutionRecord
            A prior execution with the same execution_id or idempotency_key
            was found. The caller should return an idempotent result rather
            than executing again.
        """
        # Check for duplicate execution_id (idempotent retry of the same attempt)
        if execution_id in self._by_execution_id:
            existing = self._by_execution_id[execution_id]
            logger.debug(
                "ExecutionRegistry: duplicate execution_id=%s found (outcome=%s)",
                execution_id,
                existing.outcome,
            )
            return existing

        # Check for same logical operation (same idempotency_key + same capability)
        if idempotency_key is not None:
            idem_key = f"{capability}:{idempotency_key}"
            if idem_key in self._by_idempotency_key:
                existing = self._by_idempotency_key[idem_key]
                logger.debug(
                    "ExecutionRegistry: duplicate idempotency_key=%r capability=%s found "
                    "(prior execution_id=%s outcome=%s)",
                    idempotency_key,
                    capability,
                    existing.execution_id,
                    existing.outcome,
                )
                return existing

        # Unresolved-target guard (round 3): an UNKNOWN or in-flight write to
        # the same domain target blocks this one until it is reconciled.
        if intent is not None and intent.target:
            blocking = self.unresolved_for_target(capability, intent.target)
            if blocking is not None:
                logger.warning(
                    "ExecutionRegistry: write to %s target=%s refused — prior "
                    "execution_id=%s is unresolved (%s); reconciliation required",
                    capability,
                    intent.target,
                    blocking.execution_id,
                    blocking.effective_status,
                )
                return blocking

        # Fresh start — register the record
        record = ExecutionRecord(
            execution_id=execution_id,
            idempotency_key=idempotency_key,
            capability=capability,
            proposal_id=proposal_id,
            started_at=datetime.now(timezone.utc),
            intent=intent,
        )
        self._by_execution_id[execution_id] = record
        if idempotency_key is not None:
            idem_key = f"{capability}:{idempotency_key}"
            self._by_idempotency_key[idem_key] = record

        return None

    def complete(
        self,
        execution_id: str,
        outcome: ExecutionOutcome,
        result: Any,
    ) -> None:
        """Mark an execution as complete with its final outcome and result."""
        record = self._by_execution_id.get(execution_id)
        if record is None:
            logger.warning(
                "ExecutionRegistry.complete: unknown execution_id=%s", execution_id
            )
            return
        record.outcome = outcome
        record.completed_at = datetime.now(timezone.utc)
        record.result = result

    def mark_unknown(self, execution_id: str) -> None:
        """
        Mark an execution as UNKNOWN (ambiguous write — mutation may have occurred,
        response was lost). Prevents any automatic retry.
        """
        record = self._by_execution_id.get(execution_id)
        if record is None:
            logger.warning(
                "ExecutionRegistry.mark_unknown: unknown execution_id=%s", execution_id
            )
            return
        record.outcome = ExecutionOutcome.UNKNOWN
        record.completed_at = datetime.now(timezone.utc)
        logger.warning(
            "ExecutionRegistry: execution_id=%s marked UNKNOWN — "
            "reconciliation required before re-execution",
            execution_id,
        )

    def set_reconciliation(
        self, execution_id: str, record: ReconciliationRecord
    ) -> None:
        """
        Attach a ReconciliationRecord to an UNKNOWN execution.

        The original ExecutionOutcome.UNKNOWN is NOT rewritten — this is by
        design. Use ExecutionRecord.effective_status for the derived
        operational view after reconciliation.
        """
        existing = self._by_execution_id.get(execution_id)
        if existing is None:
            logger.warning(
                "ExecutionRegistry.set_reconciliation: unknown execution_id=%s",
                execution_id,
            )
            return
        if existing.outcome != ExecutionOutcome.UNKNOWN:
            logger.warning(
                "ExecutionRegistry.set_reconciliation: execution_id=%s outcome is %s, "
                "not UNKNOWN — reconciliation record stored but outcome is unchanged",
                execution_id,
                existing.outcome,
            )
        existing.reconciliation = record
        logger.info(
            "ExecutionRegistry: reconciliation stored execution_id=%s outcome=%s",
            execution_id,
            record.outcome.value,
        )

    def get_by_execution_id(self, execution_id: str) -> ExecutionRecord | None:
        return self._by_execution_id.get(execution_id)

    def unresolved_for_target(
        self, capability: str, target: str
    ) -> ExecutionRecord | None:
        """The oldest unresolved record for the same domain + target, if any."""
        parts = capability.split(".")
        domain = parts[1] if len(parts) >= 3 else capability
        found = [
            r
            for r in self._by_execution_id.values()
            if r.unresolved and r.domain == domain and r.target == target
        ]
        return min(found, key=lambda r: r.started_at) if found else None

    def unresolved(self) -> list[ExecutionRecord]:
        """Every in-flight or unreconciled UNKNOWN record (oldest first)."""
        return sorted(
            (r for r in self._by_execution_id.values() if r.unresolved),
            key=lambda r: r.started_at,
        )

    def records(self) -> list[ExecutionRecord]:
        return sorted(self._by_execution_id.values(), key=lambda r: r.started_at)

    def get_by_idempotency_key(
        self, idempotency_key: str, capability: str
    ) -> ExecutionRecord | None:
        idem_key = f"{capability}:{idempotency_key}"
        return self._by_idempotency_key.get(idem_key)

    def __len__(self) -> int:
        return len(self._by_execution_id)

    def reset(self) -> None:
        """Clear all records. For test use only."""
        self._by_execution_id.clear()
        self._by_idempotency_key.clear()


# ── Durable registry (v2.0.1 round 3, NEW3-P1-02) ─────────────────────────────


class ExecutionJournalError(RuntimeError):
    """The durable execution journal cannot be read; writes must not proceed."""


def _dt(value: str | None) -> datetime | None:
    return datetime.fromisoformat(value) if value else None


def _record_to_dict(record: ExecutionRecord) -> dict[str, Any]:
    result = record.result
    if result is not None and hasattr(result, "model_dump"):
        result = result.model_dump(mode="json")
    rec = record.reconciliation
    return {
        "schema": 1,
        "execution_id": record.execution_id,
        "idempotency_key": record.idempotency_key,
        "capability": record.capability,
        "proposal_id": record.proposal_id,
        "started_at": record.started_at.isoformat(),
        "outcome": record.outcome.value if record.outcome is not None else None,
        "completed_at": (
            record.completed_at.isoformat() if record.completed_at else None
        ),
        "result": result,
        "intent": asdict(record.intent) if record.intent is not None else None,
        "reconciliation": (
            {
                "reconciliation_id": rec.reconciliation_id,
                "outcome": rec.outcome.value,
                "reconciled_at": rec.reconciled_at.isoformat(),
                "evidence": rec.evidence,
                "trace_id": rec.trace_id,
                "error": rec.error,
            }
            if rec is not None
            else None
        ),
        "recovered_after_restart": record.recovered_after_restart,
    }


def _record_from_dict(data: dict[str, Any]) -> ExecutionRecord:
    result = data.get("result")
    if isinstance(result, dict):
        from .base import ActionExecutionResult  # local: base imports registry

        result = ActionExecutionResult.model_validate(result)
    rec = data.get("reconciliation")
    return ExecutionRecord(
        execution_id=data["execution_id"],
        idempotency_key=data.get("idempotency_key"),
        capability=data["capability"],
        proposal_id=data["proposal_id"],
        started_at=_dt(data["started_at"]),  # type: ignore[arg-type]
        outcome=ExecutionOutcome(data["outcome"]) if data.get("outcome") else None,
        completed_at=_dt(data.get("completed_at")),
        result=result,
        intent=ExecutionIntent(**data["intent"]) if data.get("intent") else None,
        reconciliation=(
            ReconciliationRecord(
                reconciliation_id=rec["reconciliation_id"],
                outcome=ReconciliationOutcome(rec["outcome"]),
                reconciled_at=_dt(rec["reconciled_at"]),  # type: ignore[arg-type]
                evidence=rec.get("evidence") or {},
                trace_id=rec.get("trace_id"),
                error=rec.get("error"),
            )
            if rec
            else None
        ),
        recovered_after_restart=bool(data.get("recovered_after_restart")),
    )


class JsonFileExecutionRegistry(ExecutionRegistry):
    """
    ExecutionRegistry whose records are fsynced JSON files (one per
    execution_id) under ``directory``.

    * A record is written BEFORE the write is dispatched (``begin``) and
      rewritten on every transition, so a crash at any point leaves evidence.
    * On construction every record is loaded.  A record still in flight (no
      outcome) means the process died while the write may have been on the
      wire: it becomes UNKNOWN (``recovered_after_restart=True``) and keeps
      blocking its target until reconciled.  Its execution_id, proposal_id,
      decision_id and trace_id are unchanged.
    * An unreadable record raises ``ExecutionJournalError`` (fail closed: the
      executor is not built and readiness reports the governed write path
      failed) — a write must never proceed without knowing what is unresolved.

    Single node only (same as the procedure store).
    """

    def __init__(self, directory: str | Path) -> None:
        super().__init__()
        self._dir = Path(directory)
        self._dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.recovered_in_flight: list[str] = []
        for path in sorted(self._dir.glob("*.json")):
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                record = _record_from_dict(data)
            except Exception as exc:  # noqa: BLE001 — fail closed below
                raise ExecutionJournalError(
                    f"unreadable execution record {path}: {type(exc).__name__}: {exc}"
                ) from exc
            if record.outcome is None:
                record.outcome = ExecutionOutcome.UNKNOWN
                record.completed_at = datetime.now(timezone.utc)
                record.recovered_after_restart = True
                self.recovered_in_flight.append(record.execution_id)
            self._by_execution_id[record.execution_id] = record
            if record.idempotency_key is not None:
                key = f"{record.capability}:{record.idempotency_key}"
                self._by_idempotency_key[key] = record
            if record.recovered_after_restart:
                self._persist(record)
        if self.recovered_in_flight:
            logger.error(
                "JsonFileExecutionRegistry(%s): %d write(s) were in flight when the "
                "process stopped and are now UNKNOWN (reconciliation required): %s",
                self._dir,
                len(self.recovered_in_flight),
                self.recovered_in_flight,
            )

    @property
    def directory(self) -> Path:
        return self._dir

    # -- persistence -----------------------------------------------------------

    def _persist(self, record: ExecutionRecord) -> None:
        target = self._dir / f"{record.execution_id}.json"
        payload = json.dumps(_record_to_dict(record), sort_keys=True, default=str)
        fd, tmp = tempfile.mkstemp(dir=str(self._dir), prefix=".exec-", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp, target)
            dir_fd = os.open(str(self._dir), os.O_RDONLY)
            try:
                os.fsync(dir_fd)
            finally:
                os.close(dir_fd)
        finally:
            if os.path.exists(tmp):
                os.unlink(tmp)

    # -- transitions (persisted) -----------------------------------------------

    def begin(
        self,
        execution_id: str,
        idempotency_key: str | None,
        capability: str,
        proposal_id: str,
        intent: ExecutionIntent | None = None,
    ) -> ExecutionRecord | None:
        existing = super().begin(
            execution_id, idempotency_key, capability, proposal_id, intent=intent
        )
        if existing is None:
            # Persist BEFORE the caller dispatches the write.
            self._persist(self._by_execution_id[execution_id])
        return existing

    def complete(self, execution_id: str, outcome: ExecutionOutcome, result: Any) -> None:
        super().complete(execution_id, outcome, result)
        record = self._by_execution_id.get(execution_id)
        if record is not None:
            self._persist(record)

    def mark_unknown(self, execution_id: str) -> None:
        super().mark_unknown(execution_id)
        record = self._by_execution_id.get(execution_id)
        if record is not None:
            self._persist(record)

    def set_reconciliation(self, execution_id: str, record: ReconciliationRecord) -> None:
        super().set_reconciliation(execution_id, record)
        existing = self._by_execution_id.get(execution_id)
        if existing is not None:
            self._persist(existing)

    def reset(self) -> None:  # pragma: no cover - test helper parity
        super().reset()
        for path in self._dir.glob("*.json"):
            path.unlink()
