#!/usr/bin/env bash
set -euo pipefail

BREV_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${BREV_DIR}/docker-compose.maiw.yaml"
ENV_FILE="${BREV_DIR}/.env"
STARTUP_TIMEOUT_SECONDS="${STARTUP_TIMEOUT_SECONDS:-1800}"

if [ -z "${NVIDIA_API_KEY:-}" ]; then
  echo "Missing required NVIDIA_API_KEY environment variable." >&2
  exit 2
fi

if ! LC_ALL=C printf '%s' "$NVIDIA_API_KEY" | grep -Eq '^nvapi-[A-Za-z0-9._-]+$'; then
  echo "NVIDIA_API_KEY must begin with nvapi- and contain only letters, numbers, dots, underscores, or hyphens." >&2
  exit 2
fi

if ! printf '%s' "$STARTUP_TIMEOUT_SECONDS" | grep -Eq '^[1-9][0-9]*$'; then
  echo "STARTUP_TIMEOUT_SECONDS must be a positive integer." >&2
  exit 2
fi

if [ ! -f "$COMPOSE_FILE" ]; then
  echo "Missing ${COMPOSE_FILE}." >&2
  exit 1
fi

if [ ! -d /ephemeral ]; then
  echo "Expected Brev's persistent /ephemeral mount." >&2
  exit 1
fi

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

read_existing() {
  local key="$1"
  if [ -f "$ENV_FILE" ]; then
    grep -E "^${key}=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- || true
  fi
}

postgres_password="$(read_existing POSTGRES_PASSWORD)"
jwt_secret_key="$(read_existing JWT_SECRET_KEY)"

if [ -z "$postgres_password" ]; then
  postgres_password="$(random_hex)"
fi

if [ -z "$jwt_secret_key" ]; then
  jwt_secret_key="$(random_hex)$(random_hex)"
fi

echo "Configuring Docker and containerd storage under /ephemeral..."
sudo systemctl stop docker.socket || true
sudo systemctl stop docker || true
sudo systemctl stop containerd || true

sudo mkdir -p \
  /ephemeral/docker \
  /ephemeral/containerd \
  /ephemeral/maiw/postgres \
  /ephemeral/maiw/redis \
  /ephemeral/maiw/kafka \
  /ephemeral/maiw/etcd \
  /ephemeral/maiw/minio \
  /ephemeral/maiw/milvus \
  /ephemeral/maiw/nim-cache \
  /ephemeral/maiw/nim-models \
  /etc/docker \
  /etc/containerd

sudo tee /etc/docker/daemon.json >/dev/null <<'EOF'
{
  "data-root": "/ephemeral/docker",
  "default-runtime": "nvidia",
  "mtu": 8950,
  "runtimes": {
    "nvidia": {
      "args": [],
      "path": "nvidia-container-runtime"
    }
  }
}
EOF

sudo tee /etc/containerd/config.toml >/dev/null <<'EOF'
disabled_plugins = ["cri"]

root = "/ephemeral/containerd"
EOF

sudo rm -rf /var/lib/containerd
sudo ln -sfn /ephemeral/containerd /var/lib/containerd

sudo systemctl start containerd
sudo systemctl start docker.socket
sudo systemctl start docker

for _ in $(seq 1 30); do
  if docker info >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

if ! docker info >/dev/null 2>&1; then
  echo "Docker did not become ready." >&2
  exit 1
fi

echo "Generating blueprint environment configuration..."
umask 077
tmp_env="$(mktemp "${BREV_DIR}/.env.tmp.XXXXXX")"
login_output="$(mktemp)"

cleanup() {
  rm -f -- "$tmp_env" "$login_output"
}
trap cleanup EXIT

{
  printf '%s\n' '# Generated by deploy/brev/startup.new.sh.'
  printf '%s\n' '# Do not commit this file.'
  printf '%s\n' ''
  printf '%s\n' 'ENVIRONMENT=development'
  printf '%s\n' ''
  printf '%s\n' 'POSTGRES_USER=warehouse'
  printf 'POSTGRES_PASSWORD=%s\n' "$postgres_password"
  printf '%s\n' 'POSTGRES_DB=warehouse'
  printf '%s\n' 'DB_HOST=timescaledb'
  printf '%s\n' 'DB_PORT=5432'
  printf '%s\n' 'PGPORT=5435'
  printf '%s\n' ''
  printf 'JWT_SECRET_KEY=%s\n' "$jwt_secret_key"
  printf '%s\n' 'REDIS_HOST=redis'
  printf '%s\n' 'REDIS_PORT=6379'
  printf '%s\n' 'REDIS_PASSWORD='
  printf '%s\n' 'REDIS_DB=0'
  printf '%s\n' ''
  printf '%s\n' 'MILVUS_HOST=milvus'
  printf '%s\n' 'MILVUS_PORT=19530'
  printf '%s\n' 'MILVUS_USER=root'
  printf '%s\n' 'MILVUS_PASSWORD=Milvus'
  printf '%s\n' 'MILVUS_USE_GPU=true'
  printf '%s\n' 'MILVUS_GPU_DEVICE_ID=0'
  printf '%s\n' 'CUDA_VISIBLE_DEVICES=0,1,2,3'
  printf '%s\n' 'MILVUS_INDEX_TYPE=GPU_CAGRA'
  printf '%s\n' 'MILVUS_COLLECTION_NAME=warehouse_docs_gpu'
  printf '%s\n' ''
  printf '%s\n' 'KAFKA_BOOTSTRAP_SERVERS=kafka:9092'
  printf '%s\n' ''
  printf '%s\n' 'MINIO_ROOT_USER=minioadmin'
  printf '%s\n' 'MINIO_ROOT_PASSWORD=minioadmin'
  printf '%s\n' 'MINIO_ACCESS_KEY=minioadmin'
  printf '%s\n' 'MINIO_SECRET_KEY=minioadmin'
  printf '%s\n' ''
  printf 'NVIDIA_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'EMBEDDING_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'RAIL_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'NEMO_RETRIEVER_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'NEMO_OCR_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'NEMO_PARSE_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'LLAMA_NANO_VL_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf 'LLAMA_49B_API_KEY=%s\n' "$NVIDIA_API_KEY"
  printf '%s\n' ''
  printf '%s\n' 'LLM_NIM_IMAGE=nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1.5:2.0.6'
  printf '%s\n' 'LLM_NIM_URL=http://llm-nim:8000/v1'
  printf '%s\n' 'LLM_NIM_PORT=8000'
  printf '%s\n' 'LLM_MODEL=nvidia/llama-3.3-nemotron-super-49b-v1.5'
  printf '%s\n' 'LLM_TEMPERATURE=0.1'
  printf '%s\n' 'LLM_MAX_TOKENS=2000'
  printf '%s\n' 'LLM_TOP_P=1.0'
  printf '%s\n' 'LLM_FREQUENCY_PENALTY=0.0'
  printf '%s\n' 'LLM_PRESENCE_PENALTY=0.0'
  printf '%s\n' 'LLM_CLIENT_TIMEOUT=120'
  printf '%s\n' 'LLM_CACHE_ENABLED=true'
  printf '%s\n' 'LLM_CACHE_TTL_SECONDS=300'
  printf '%s\n' ''
  printf '%s\n' 'EMBEDDING_NIM_URL=https://integrate.api.nvidia.com/v1'
  printf '%s\n' 'EMBEDDING_MODEL=nvidia/llama-nemotron-embed-vl-1b-v2'
  printf '%s\n' 'EMBEDDING_DIMENSION=2048'
  printf '%s\n' ''
  printf '%s\n' 'RAIL_API_URL=https://integrate.api.nvidia.com/v1'
  printf '%s\n' 'LLAMA_49B_TIMEOUT=120'
  printf '%s\n' ''
  printf '%s\n' 'CORS_ORIGINS=http://localhost:3001,http://localhost:3000,http://127.0.0.1:3001,http://127.0.0.1:3000'
  printf '%s\n' 'MAX_REQUEST_SIZE=10485760'
  printf '%s\n' 'MAX_UPLOAD_SIZE=52428800'
} > "$tmp_env"

mv "$tmp_env" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "Authenticating Docker with nvcr.io..."
if ! printf '%s' "$NVIDIA_API_KEY" \
  | docker login nvcr.io -u '$oauthtoken' --password-stdin >"$login_output" 2>&1; then
  echo "Could not authenticate with nvcr.io using NVIDIA_API_KEY." >&2
  sed 's/^/  /' "$login_output" >&2
  exit 1
fi

cd "$BREV_DIR"

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

echo "Pulling blueprint images..."
compose pull --quiet --ignore-buildable

echo "Building blueprint application images..."
compose build --quiet

echo "Starting the blueprint..."
compose up \
  -d \
  --quiet-pull \
  --quiet-build \
  --remove-orphans \
  --wait \
  --wait-timeout "$STARTUP_TIMEOUT_SECONDS"

echo "Multi Agent Intelligent Warehouse is ready on port 3001."
